from prepare import *
REFS=[
 ('S34-ATTIC','DOE: Durable attics','https://www.energy.gov/sites/default/files/2021-08/ES-Durable%20Attics_081221.pdf','Read insulation, air leakage, moisture and the actual roof assembly together.'),
 ('S34-AIR','DOE: Air sealing','https://www.energy.gov/sites/default/files/2021-08/ES-Air%20Sealing_080421.pdf','Air leakage and thermal insulation are separate mechanisms; ventilation and combustion safety remain part of the system.'),
 ('S34-VERM','EPA: Vermiculite attic insulation','https://www.epa.gov/asbestos/my-attic-has-vermiculite-insulation-it-am-i-risk-should-i-take-it-out','Assume vermiculite insulation may be asbestos contaminated; leave it undisturbed and use appropriate specialist advice.')]
def refs(t):return [dict(source='S34',seconds=t,label='Reviewed insulation / ventilation lesson')]+[dict(source=a,label=b,url=c) for a,b,c,e in REFS]
def topic(id,title,rows,t):return dict(id=id,title=title,section='Roof structure, insulation and ventilation',blocks=[dict(kind='table',headers=['Distinction','Read / record','Limit / next question'],rows=rows,widths=[108,225,171])],refs=refs(t))
NEW=[topic('insulation_materials','Insulation: product, continuity and installed evidence',[
 ['Identify the material','Record accessible form, label, thickness variation, gaps, compression, displacement and wetting. Distinguish batts, loose fill, rigid board and sprayed foam.','Color alone is not positive identification. Do not disturb suspect hazardous material or conceal an access limitation.'],
 ['Installed R-value','Use the specific product chart and installation conditions. Retain measured locations and units; compare accessible areas rather than inventing a whole-house value.','Generic R/inch is a study approximation. Thickness alone and an installer\'s card alone do not prove installed performance.'],
 ['Loose-fill coverage','Compare product, claimed bag count/area, minimum installed depth and settled depth. Note inaccessible or compressed regions.','Both density/coverage and thickness matter. An old card does not establish that today\'s insulation is unchanged.'],
 ['Contact / continuity','Check contact with the intended thermal boundary, framing interfaces, penetrations and open gaps. Preserve designed ventilation space where required.','Do not call every exposed framing member or every uninsulated porch roof a defect; identify conditioned versus unconditioned space first.'],
 ['Heat / wiring / foam','Observe listed clearances and accessible fixture ratings, wiring conditions and exposed foam protection.','Never bury an unidentified hot fixture or flue, treat all foam as the same product, or prescribe a generic fire-protection detail.'],
 ['Vermiculite concern','Record a suspected material from safe access, limit disturbance and refer for appropriate evaluation before work.','EPA advises treating vermiculite insulation as potentially asbestos contaminated. A brand guess or ordinary visual inspection cannot clear it.']],633),
 topic('air_vapor_thermal','Four mechanisms: heat flow, air leakage, vapor and radiation',[
 ['Thermal insulation','Slows heat transfer. Coverage, thickness, density, fit and moisture affect the assembly.','An R-value label is not an air-sealing or whole-assembly performance claim.'],
 ['Air barrier','Controls bulk air movement through a continuous sealed boundary and its joints/penetrations.','Insulation, stapled foil or kraft facing does not automatically create that continuous boundary.'],
 ['Vapor retarder','Limits vapor diffusion; locate it by product, climate, layer sequence and drying strategy.','Do not impose one universal warm-side rule or diagnose trapped moisture from two layers alone. Verify permeability and the whole assembly.'],
 ['Radiant barrier','A reflective low-emittance surface acts across an adjacent air space; dust and installation geometry affect usefulness.','It is not interchangeable with bulk insulation or an unconditional R-value. Do not repeat a generic three-year failure or fixed temperature-saving claim.'],
 ['Vented / unvented','Locate thermal and air boundaries at the ceiling, roofline, floor or perimeter as actually constructed.','Closed vents and sprayed foam alone do not establish a complete conditioned attic or crawlspace system.'],
 ['Coupled changes','Air sealing, exhaust and combustion interact. Record relevant equipment and ventilation provisions when considering improvements.','Do not prescribe tighter enclosure, a powered fan or closed crawl vents without the complete moisture/ventilation/combustion plan.']],1654),
 topic('ventilation_exhaust','Ventilation: distinguish the air paths before judging them',[
 ['Attic intake / outlet','In a vented attic, examine intended low/high paths, baffles, blocked soffits and connections to roof form.','Use manufacturer net-free-area data and the applicable design. Gross opening area divided by two is not a universal calculation.'],
 ['Fan types','A room exhaust, whole-house cooling fan, powered attic ventilator and balanced ventilation unit serve different spaces and purposes.','A powered attic fan may draw conditioned air through ceiling leaks. Fan noise alone does not establish airflow or a safe pressure balance.'],
 ['Bathroom / dryer / hood','Trace accessible discharge to the intended exterior terminal; look for disconnected joints, inappropriate duct and recirculation into intakes.','Keep room exhaust, combustion venting, plumbing vents and attic ventilation separate. An unseen end remains unverified.'],
 ['Moisture pattern','Record stained/wet sheathing, rusty fasteners, wet insulation and nearby sources. Compare levels and weather/test conditions.','Uniform staining is not proof of ventilation failure, nor is an isolated stain proof of a roof leak. Do not identify mold species or historic cause by appearance.'],
 ['Ice dam mechanism','Heat reaching snow-covered roofing can melt snow; refreezing at colder eaves can back water under the covering.','Assess ceiling leakage, insulation continuity and the actual vented/unvented design. Heat cable is not proof that the underlying cause is resolved.'],
 ['Access / report','Record entry method, inspected extent and each inaccessible region, including areas below fixtures.','A safe-size opening does not make the space safe. Do not imply complete access because entry was possible.']],6083)]
TERMS=[
 ('Air barrier','Bulk-airflow control layer','Controls air leakage and is a different function from a vapor retarder; continuity across joints and penetrations decides performance, and insulation or a facing alone does not create it.','air_vapor_thermal'),
 ('Net free ventilating area','Usable opening after restrictions','The effective open vent area after louvers, screens and other restrictions; use the product data rather than a universal fraction.','ventilation_exhaust'),
 ('Radiant barrier','Low-emittance surface at an air space','Reduces radiant heat transfer in the designed configuration; not a substitute for all insulation or air sealing.','air_vapor_thermal'),
 ('Ice dam','Refreezing meltwater at a colder roof edge','A water-backup mechanism connected to roof temperatures, weather and the envelope; an icicle alone does not identify every cause.','ventilation_exhaust'),
 ('Vermiculite','Granular insulation requiring disturbance caution','Potentially asbestos-contaminated attic insulation; appearance does not establish asbestos absence.','insulation_materials')]
def apply(d,compact,apps,walk):
 i=next(i for i,p in enumerate(d['pages']) if p['id']=='attic_environment')+1;d['pages'][i:i]=copy.deepcopy(NEW)
 topics={p['id']:p for p in d['pages']}
 for tid in ['crawl_moisture','crawl_openings']:
  topics[tid]['blocks'].append(dict(kind='text',text='S34 REVIEW: evaluate the complete vented or unvented crawlspace strategy: ground-water control, ground cover, perimeter/floor insulation, drying and services. Do not close vents as an isolated repair. Describe the exact inaccessible region and its remaining question.'))
  topics[tid]['refs']+=refs(5201)
 compact.append(dict(id='insulation',title='25  Insulation, ventilation and moisture',route='Boundary > mechanism > route > evidence',topics=[p['id'] for p in NEW],rows=[
 ['Find the boundary','Identify ceiling versus roofline, floor versus crawl perimeter and the conditioned spaces.','No blanket missing-vent or uninsulated-framing conclusion.'],
 ['Read the insulation','Record product, depth variation, coverage, gaps, compression and wetting.','Card, bag count and depth are evidence to compare; none alone certifies installed R-value.'],
 ['Separate controls','Insulation slows heat; an air barrier limits airflow; a vapor retarder limits diffusion.','Position and permeability depend on climate and the whole assembly.'],
 ['Trace ventilation','Follow intake, outlet, baffles and the actual fan/duct/termination.','Net free area is product-specific. Powered airflow can interact with conditioned space and combustion.'],
 ['Connect the water','Compare roof sheathing, fixtures/exhaust, ceiling leaks and conditions below.','Stain distribution suggests questions; it does not prove cause or identify mold.'],
 ['Respect material / access','Suspected vermiculite, unsafe footing, exposed wiring or inaccessible regions change the method.','Leave suspect material undisturbed; record extent and obtain appropriate follow-up.']],discuss='Are we trying to control heat, moving air, vapor diffusion, rainwater or exhaust?',note='S34 / N11. Product and design conditions stay with every number. Source PDFs: DOE Durable Attics and Air Sealing; EPA material guidance in APP-E.',figure=None))
 merge_term(apps,'Vapor retarder','S34: limits diffusion, not bulk airflow (see Air barrier); permeability, climate, layer sequence and drying strategy decide the assembly.','air_vapor_thermal',topics['air_vapor_thermal']['title']+' / S34',topics['air_vapor_thermal']['refs'])
 for term,exp,definition,tid in TERMS:apps['APP-D']['terms'].append(dict(term=term,expansion=exp,definition=definition,topic=tid,source_pointer=topics[tid]['title']+' / S34',source_refs=topics[tid]['refs']))
 apps['APP-D']['notes'].append(['N11','Envelope mechanisms and numerical limits','Do not substitute insulation for air sealing, use gross vent area as net free area, infer R-value from depth alone, or diagnose moisture solely by stain pattern. Product, climate, assembly and access govern interpretation.'])
 apps['APP-E']['external_references'] +=[dict(id=a,title=b,url=c,note=e,reviewed_on='2026-09-21') for a,b,c,e in REFS]
 for title,note,tid in [('Insulation evidence','Record product/label, depth locations, gaps, compression, moisture and scope of visibility.','insulation_materials'),('Ventilation and exhaust routes','Record actual fan type, connected route, terminal and obstruction; distinguish unseen ends.','ventilation_exhaust'),('Thermal / air / vapor boundary','Identify the assembly and moisture/control question before recommending a change.','air_vapor_thermal')]:
  n=len(apps['APP-C']['items'])+1;apps['APP-C']['items'].append(dict(id=f'M{n:04}',added='2026-09-21',mention=title,note=note,source='S34 / '+tid,links=[],status='Report prompt; no property finding',checklist_status='Not a property checklist'))
 upper=next(p for p in walk if p['id']=='upper');upper['refs'].append('insulation')
 upper['note']='Record the actual thermal boundary, depth/coverage, air paths and exhaust endpoints. Do not disturb suspect vermiculite. Stain patterns guide follow-up; they do not prove cause. Keep access limits spatially specific.'
