TERMS=[
 ('AFCI','Arc-fault circuit interrupter','Detects certain arcing faults; distinct from GFCI protection.','electric_devices'),
 ('AFUE','Annual fuel utilization efficiency','Seasonal useful heat output as a fraction of fuel energy input; not the percentage of fuel chemically burned.','furnace_types'),
 ('AWG','American Wire Gauge','Conductor-size designation. Material, insulation, terminals and application still govern suitability.','electric_conductors'),
 ('CO','Carbon monoxide','Toxic combustion gas; a combustible-gas detector and a CO instrument serve different purposes.','furnace_safety'),
 ('CSST','Corrugated stainless steel tubing','Fuel-gas distribution tubing; distinguish product type, bonding requirements and appliance connectors.','gas_piping'),
 ('DWV','Drain, waste and vent','Piping that carries waste and admits air; separate from the potable supply and relief piping.','backflow_dwv'),
 ('EIFS','Exterior insulation and finish system','Exterior wall finish assembly; distinguish its layers and drainage details from conventional stucco.','siding_eifs'),
 ('EMT','Electrical metallic tubing','A raceway; verify fittings and suitability for the exposure.','electric_wiring_methods'),
 ('FAC','Flexible appliance connector','Final fuel-gas connection to an appliance; not interchangeable with CSST distribution tubing.','gas_piping'),
 ('FVIR','Flammable vapor ignition resistant','A product feature; does not by itself settle every garage installation requirement.','garage_appliances'),
 ('GFCI','Ground-fault circuit interrupter','Protection against certain ground-fault shock hazards; a successful test does not certify the whole circuit.','electric_devices'),
 ('MWBC','Multiwire branch circuit','A circuit arrangement sharing a neutral; supply legs and disconnect provisions matter.','electric_multiwire'),
 ('NM cable','Nonmetallic-sheathed cable','Cable with a nonmetallic outer sheath; check marking and application, including moisture exposure.','electric_wiring_methods'),
 ('T&P / TPR','Temperature-and-pressure relief','Relief protection with distinct temperature and pressure functions; do not confuse it with a pan drain.','water_heater_relief'),
 ('Rake / eave','Roof-edge terms','Rake: sloped edge at a gable end. Eave: lower roof edge where runoff normally leaves the plane.','roof_forms'),
 ('Grounding / bonding','Electrical connection functions','Grounding connects to earth; bonding joins conductive parts to establish the intended electrical continuity and fault-current path.','electric_service'),
 ('Gravity / forced air','Heating distribution methods','Gravity uses natural air circulation; forced air uses a blower. Neither term establishes combustion venting type.','gravity_furnaces'),
 ('COURSE / EXAM','Source flags','Training statement / recorded assessment concept. Neither alone establishes current local requirements.','inspection_method'),
 ('NOTE / LOCAL','Review flags','Reviewed explanation or correction / jurisdiction-specific qualification requiring the stated scope.','local_amendments'),
 ('Load path','Structural sequence','Route by which loads pass through connected members and bearing points to the foundation and ground.','supports'),
 ('Footing / foundation','Supporting elements','A footing spreads loads to supporting ground; the foundation transfers building loads to its support. Identify the visible assembly.','foundation_types'),
 ('Differential movement','Unequal movement','Parts of an assembly move by different amounts; crack patterns alone do not establish the cause or whether movement is active.','movement'),
 ('Capillary action','Moisture movement','Liquid movement through fine pores or narrow spaces; distinguish it from bulk runoff and vapor transport.','moisture'),
 ('Efflorescence','Mineral deposit','Surface salts left as moisture evaporates; evidence of moisture transport, not proof of an active leak at the visit.','masonry_distress'),
 ('Spalling','Surface deterioration','Flaking, breaking or loss of material at a masonry or concrete surface. Describe location and extent before assigning a cause.','masonry_distress'),
 ('Vapor retarder','Vapor-control layer','Material that limits water-vapor diffusion. Its presence alone does not establish a complete moisture-control system.','crawl_moisture'),
 ('Flood opening / air vent','Different opening functions','Flood openings address hydrostatic pressure equalization; ventilation openings address air movement. Do not use one label for both.','crawl_openings'),
 ('Joist / beam / girder','Floor support members','Joists commonly carry floor/decking loads to beams or girders; confirm actual bearing and connection, not just member size.','supports'),
 ('Bearing / connection','Load transfer','Bearing transfers load at a support surface; a connection secures or transfers forces between members. Both need context.','engineered_and_connections'),
 ('Notch / bored hole','Different member cuts','An edge cut and an enclosed hole affect a member differently; use the applicable member-specific limits.','notches_and_holes'),
 ('Cantilever','Projecting member','A member extending beyond its support. Backspan, connection and loads affect the assembly.','cantilevers_openings'),
 ('Post-tensioned slab','Prestressed concrete assembly','Tendons stressed after concrete placement; drilling or cutting can intersect concealed stressed tendons.','post_tension'),
 ('Rafter / truss','Roof framing forms','An individual sloping member versus an interconnected designed assembly. Do not apply ordinary rafter alteration assumptions to a truss.','roof_trusses'),
 ('Collar tie / rafter tie','Different tie functions','Upper ties and lower ties serve different functions and locations; identify the complete roof design.','roof_ties'),
 ('Truss uplift / rafter spread','Different movement mechanisms','Uplift is upward truss-chord movement; spread is outward movement at rafter supports. Similar finish cracks require surrounding evidence.','roof_frame'),
 ('Veneer','Nonstructural facing','A facing supported and attached to another assembly; distinguish it from structural masonry.','masonry_systems'),
 ('WRB','Water-resistive barrier','Layer within the wall water-control assembly; its continuity and integration with flashing matter.','siding_assembly'),
 ('Weep / drainage plane','Water exit and route','A weep is an opening for drainage; the drainage plane is the path behind the cladding. A visible hole does not establish the concealed path.','siding_veneer_details'),
 ('Step / counter / kick-out flashing','Roof-wall water management','Step pieces interleave with roofing; counterflashing covers an upper flashing edge; a kick-out redirects water at the lower end.','roof_flashing'),
 ('Fascia / soffit / frieze','Exterior trim locations','Fascia follows the roof edge; soffit is the underside of an overhang; frieze is trim near the top of the wall.','trim_parts'),
 ('Sash / glazing / IGU','Window parts','Sash holds glazing; an insulated glass unit combines sealed panes. Distinguish seal failure from surface condensation.','window_glazing'),
 ('U-factor / SHGC','Different window ratings','U-factor describes heat transfer; solar heat gain coefficient describes admitted solar heat. Keep units, climate and label context.','window_energy'),
 ('Ledger / guard / handrail','Deck and stair functions','Ledger transfers deck loads to a support; guard limits falls at an edge; handrail provides a graspable support.','rails_guards'),
 ('Grade / retaining wall','Site form and support','Grade is the ground slope/elevation; a retaining wall supports a difference in ground level. Trace drainage and visible movement.','retaining_wall_types'),
 ('Functional flow / drainage','Different plumbing observations','Flow concerns usable supply while fixtures operate; drainage concerns waste leaving fixtures. Record the actual test and response.','water_supply'),
 ('Cross-connection / air gap','Potable-water protection','A cross-connection can expose supply water to contamination; an air gap is a physical separation used in appropriate protection arrangements.','backflow_dwv'),
 ('Trap / vent','Waste-system functions','A trap retains a water seal; a vent manages air movement in the drainage system. Neither is a supply backflow device.','backflow_dwv'),
 ('Dielectric connection','Dissimilar-metal separation','A suitable connection limits direct electrical contact between dissimilar metals. Thread tape alone is not a listed dielectric fitting.','plumbing_materials'),
 ('Draft hood / barometric damper','Different draft devices','A gas draft hood and a swinging barometric regulator have different arrangements; match the appliance, fuel and vent system.','oil_draft'),
 ('Heat exchanger','Separated heat-transfer surfaces','Transfers heat between streams while intended to keep combustion products separate from the distributed heating medium. Visibility is limited.','furnace_types'),
 ('Thermocouple / photocell','Different flame-sensing methods','A thermocouple generates a small temperature-related voltage; a photocell senses light. Controls and service procedures are system-specific.','furnace_safety'),
 ('Condensing equipment','Latent-heat recovery','Equipment designed to recover heat as water vapor condenses; requires compatible venting and condensate arrangements.','furnace_types'),
 ('IC / IC-AT','Recessed-light ratings','Insulation-contact / insulation-contact with air-tight designation. Verify the actual product and installation conditions, not paint color.','electric_devices'),
 ('AHJ','Authority having jurisdiction','The responsible authority for the address, work and code family; county boundaries alone may not identify the permit authority.','APP-H'),
 ('Code / standard / general practice','Different bases for a statement','Adopted legal requirements, referenced technical provisions and customary practice have different authority and scope. Keep the qualifier attached.','APP-H'),
 ('Model edition / effective date','Different dates','A model-code publication year does not establish when a locality applied it. Record adoption, effective date and permit transition separately.','APP-H'),
 ('IBC / IRC','International Building Code / International Residential Code','Different code scopes; establish which applies to the building and work, with local amendments.','APP-H'),
 ('IECC / IEBC','International Energy Conservation Code / International Existing Building Code','Energy and existing-building provisions have distinct scopes and adoption histories.','APP-H'),
 ('IPC / IMC / IFGC','International Plumbing / Mechanical / Fuel Gas Code','Separate code families; local adoption and amendments may differ.','APP-H'),
 ('NEC / NFPA 70','National Electrical Code','Two identifiers for the electrical code; distinguish the edition from local adoption and enforcement dates.','APP-H'),
 ('NFPA','National Fire Protection Association','Standards publisher. NFPA 1, 54, 70 and 101 address different subjects; the organization name alone is not a requirement citation.','APP-H'),
 ('BOCA / CABO','Historical model-code organizations','Building Officials and Code Administrators / Council of American Building Officials. The historical local record must identify the particular code and edition.','APP-H'),
 ('EVSE / EV-ready','Electric vehicle supply equipment / charging provision','Installed charging equipment differs from provisions for future equipment. Read the applicable statute, permit scope and actual labels.','APP-H'),
 ('Home inspection / code compliance','Different conclusions','An inspection reports observed conditions within its scope; it does not by itself certify compliance with every applicable construction requirement.','inspection_method')]
